<a href="https://colab.research.google.com/github/swati-sh/PIKTORML/blob/master/Assignment_1/Copy_of_Assignment_1c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PIKTORML Python Assignment

**DISCLAIMER : Plagiarism is strictly prohibited. This is a best practise for your good. If copied then you are fooling yourself**

##Introduction

You will be given a question and the code for it should be added with a code block cell added just below it with comments which explain the code

For example

***
Example Question:

Write a program :

A function which implements quicksort on an array input to it and returns a sorted array
***

In [0]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print quicksort([3,6,8,10,1,2,1])

**Question 1: (30 points)(20 for code 10 for comments)**

Write a function which does a mtrix multiplication on two arrays input to it

Hint : Use nested loops, AB is not always equal to BA in matrices

In [4]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
y = np.array([[2,2,2],[1,5,6],[9,3,2]])
#creating a matrix res with the same shape as x
res = np.empty_like(x)
# iterate through rows of x
for i in range(len(x)):
   # iterate through columns of y
   for j in range(len(y[0])):
       # iterate through rows of y
       for k in range(len(y)):
           res[i][j] += x[i][k] * y[k][j] 
#itterate through res
for r in res:
   print(r)

[33 23 22]
[68 56 56]
[112  84  82]
[32 23 23]


**Question 2: (40 points)(30 for code 10 for comments)**

Define a class named Circle which can be constructed by a radius. The Circle class has a method which can compute the area. 

Print the area of a circle object defined by the class you created with radius 3

In [12]:
class Circle:
   # Constructor
    def __init__(self, radius):
        self.radius = radius  # Create an instance variable

    # Instance method
    def area(self):
             areaofcircle= 3.14*self.radius**2 #declare a varible that contain calculated area of circle
             print (areaofcircle)

g = Circle(3)  # Construct an instance of the Circle class
g.area()            # Call an instance method; prints area of circle

28.26


**Question 3: (60 points)(50 for code 10 for comments)**

Write a program to compute:

f(n)=f(n-1)+100 when n>0
and f(0)=1

with a given n input (n>0).

Example:
If the following n is given as input to the program:

5

Then, the output of the program should be:

500

In case of input data being supplied to the question, it should be assumed to be a console input.

Hints:
We can define recursive function in Python.

In [14]:
def rec(x):
  if(x==0): #if the value of x is 0 then it will return 0
    return 0
  else:
    return rec(x-1)+100 #recursively the function rec is being called

print (recursion(5))

500


**Question 4**: (**120 points)(60 for code 60 for comments)**

***This is a bonus question to prove your mettle to the world***

***Even if you are not able to solve this it won't be graded but if you are able to solve it you get bonus points***

It is possible to write ten as the sum of primes in exactly five different ways:

* 7 + 3
* 5 + 5
* 5 + 3 + 2
* 3 + 3 + 2 + 2
* 2 + 2 + 2 + 2 + 2

What is the **first value** which can be written as the sum of primes in **over** five thousand different ways?

Write a program(a function) to solve the above problem to a generic input value and returns the first value which can be written in >= the input value times 

Print the value for input = 5000

In [0]:
#your code here

**END OF ASSIGNMENT**